name: system_settings
description: Flutter plugin to open system and app settings on iOS and Android.
version: 2.0.0
homepage: https://github.com/fweinaug/system_settings
repository: https://github.com/fweinaug/system_settings

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0 <2.0.3"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.florianweinaug.system_settings
        pluginClass: SystemSettingsPlugin
      ios:
        pluginClass: SystemSettingsPlugin
